/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#a1cfce',
        background: '#faf8ff',
        'secondary-fixed-dim': '#81d1f0',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#00647d',
        'tertiary-container': '#457171',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        outline: '#6e7977',
        'surface-bright': '#faf8ff',
        'surface-container': '#eaedff',
        secondary: '#006781',
        'primary-fixed': '#9cf2e8',
        'surface-container-low': '#f2f3ff',
        'on-primary-container': '#a3faef',
        'on-background': '#131b2e',
        'inverse-primary': '#80d5cb',
        tertiary: '#2c5858',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#bdc9c6',
        error: '#ba1a1a',
        'secondary-container': '#8fdfff',
        'on-surface': '#131b2e',
        'on-tertiary-fixed': '#002020',
        'on-surface-variant': '#3e4947',
        surface: '#faf8ff',
        'surface-tint': '#006a63',
        'primary-fixed-dim': '#80d5cb',
        'surface-variant': '#dae2fd',
        'on-tertiary-container': '#c4f3f2',
        'on-primary-fixed': '#00201d',
        'surface-container-highest': '#dae2fd',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#204e4d',
        primary: '#005c55',
        'primary-container': '#0f766e',
        'inverse-surface': '#283044',
        'on-secondary-fixed': '#001f29',
        'surface-container-high': '#e2e7ff',
        'inverse-on-surface': '#eef0ff',
        'on-secondary-fixed-variant': '#004d62',
        'secondary-fixed': '#b9eaff',
        'tertiary-fixed': '#bdebea',
        'on-error': '#ffffff',
        'surface-dim': '#d2d9f4',
        'on-primary-fixed-variant': '#00504a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '1rem',
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
        'margin-desktop': '2rem',
        margin: '1rem',
        'gutter-desktop': '1.5rem',
        'space-md': '0.75rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'display-lg': ['"Plus Jakarta Sans"'],
        'body-sm': ['Inter'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
        'body-md': ['Inter'],
        'data-mono': ['Inter'],
        'display-lg-mobile': ['"Plus Jakarta Sans"'],
        'label-md': ['Inter'],
        'label-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-sm': ['"Plus Jakarta Sans"'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'data-mono': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
